### ISSUE TITLE
REST API calls return "Unauthenticated since user could not be found or created"

### ISSUE THREAD

**Issue by vikramaraja** [szemek/teamcity-saml#2]
The plugin works perfect with SAML login with MFA and SSO enabled from Azure AD portal.

When HTTP-SAML2.0 plugin is at the top of the HTTP authentication modules, SAML login works fine. The API calls fails with the error "Unauthenticated since user could not be found or created".

When Basic HTTP module is at the top of the list in authentication, API calls with username/password works fine. But then SAML login fails with the same error "Unauthenticated since user could not be found or created".

Are these plugins blocking the request to dig through rest of the authentication methods if one is not available?

Regards,
Vikram

**Comment by szemek** [comment]
@vikramaraja I merged changes from pull request https://github.com/szemek/teamcity-saml/pull/3 that should solve this problem.
